ALTER TABLE messages ALTER COLUMN content SET NOT NULL;
ALTER TABLE messages ALTER COLUMN author_name SET NOT NULL;
ALTER TABLE messages ALTER COLUMN sent_at SET NOT NULL;
ALTER TABLE chats ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE chats ALTER COLUMN title SET NOT NULL;