apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chat
data:
  POSTGRES_DB: chat
  POSTGRES_HOST: db
  POSTGRES_USER: postgres
  POSTGRES_PORT: "5432"
  RUST_LOG: info
  ALLOWED_ORIGIN: http://localhost
  REDIS_URL: redis://redis:6379
